services:
  frontend:
    container_name: frontend
    build:
      context: . #if your Dockerfile is not at the same level change the path here (./frontend)
      target: dev
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
      #if you’re using Windows, you may need to uncomment the next line - Sol from @Kobe E
      #- WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./src/app
          action: sync
          target: /app/src/app
          ignore:
            - node_modules/
